language: python
sudo: false

matrix:
  include:
    - python: '3.7'
      dist: xenial  # https://github.com/travis-ci/travis-ci/issues/9815
      sudo: true

# install other libraries using pip
install:
  - pip install -U setuptools coveralls
  - pip install -Ue .[dev]
  - wget https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - unzip protoc-3.6.1-linux-x86_64.zip
  - PATH=./bin:$PATH
  - invoke protoc

# command to run tests
script:
  - pytest
  - coveralls
